name: gh-pages build
 
on:
  push:
    branches:
      - main
  #schedule:   
   # - cron: '0 5 * * *'   #国际标准时间，北京时间+8，即下午1点钟
 
jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '16'
      
      - name: Install Dependency       
        run: |
          npm install        
          npm run build  # 构建build
          
      - name: github branch
        run: |
          git --work-tree build add --all
          git --work-tree build commit -m "updated GitHub Pages"
          git push:origin HEAD:gh-pages --force
          git checkout -f main
          
